version: "3.9"

services:
  shopping-todo-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: "always"
    container_name: "shopping-todo-dev"
    ports:
      - "3000:3000"
    volumes:
      - ./:/shopping-todo-dev
      - /shopping-todo-dev/node_modules
      - /shopping-todo-dev/.next